#version 460

layout(local_size_x = 8, local_size_y = 8) in;

layout(push_constant) uniform PushConstants {
    float radius;
} pc;

layout(set = 0, binding = 0, rgba8) uniform writeonly image2D img;
layout(set = 1, binding = 0, rgba32ui) readonly uniform uimage3D voxelImage;

void main() {
    ivec2 size = imageSize(img);
    ivec2 pixel = ivec2(gl_GlobalInvocationID.xy);

    ivec3 texel_coord = ivec3(0, 0, 0);
    uvec4 texel = imageLoad(voxelImage, texel_coord);

    if (pixel.x >= size.x || pixel.y >= size.y) {
        return; // out of bounds
    }

    // Normalize coords to [0,1]
    vec2 uv = vec2(pixel) / vec2(size);
    vec2 center = vec2(0.5, 0.5);
    float dist = distance(uv, center);

    vec4 color;
    if (dist < pc.radius) {
        color = vec4(texel[0], 0.0, 0.0, 1.0); // red circle
    } else {
        color = vec4(0.0, 0.0, 1.0, 1.0); // blue square background
    }

    imageStore(img, pixel, color);
}
