#version 460

layout(local_size_x = 8, local_size_y = 8) in;

layout(push_constant) uniform PushConstants {
    float radius;
} pc;

layout(set = 0, binding = 0, rgba8) uniform writeonly image2D img;
layout(set = 1, binding = 0, rgba8ui) readonly uniform uimage3D voxelImage;

bool is_collide(float x, float y) {
    int column = int(x / (1.0 / 4.0));
    int row = int(y / (1.0 / 4.0));

    ivec3 texel_coord = ivec3(column, row, 0);
    uvec4 texel = imageLoad(voxelImage, texel_coord);

    return bool(texel.r != 0);
}

void main() {
    ivec2 size = imageSize(img);
    ivec2 pixel = ivec2(gl_GlobalInvocationID.xy);

    ivec3 texel_coord = ivec3(0, 0, 0);
    uvec4 texel = imageLoad(voxelImage, texel_coord);

    if (pixel.x >= size.x || pixel.y >= size.y) {
        return; // out of bounds
    }

    // Normalize coords to [0,1]
    vec2 uv = vec2(pixel) / vec2(size);
    vec2 center = vec2(0.5, 0.5);
    float dist = distance(uv, center);

    vec4 color;
    float blue;
    if (dist < pc.radius) {
        blue = float(texel[0]);
    } else {
        blue = 0.0;
    }

    if (is_collide(uv[0], uv[1])) {
        color = vec4(1.0, 0.0, blue, 1.0); // blue square background
    } else {
        color = vec4(0.0, 0.0, blue, 1.0); // blue square background
    }

    imageStore(img, pixel, color);
}
